# Generated by Django 2.2.3 on 2020-01-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pacijent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default='', max_length=50)),
                ('prezime', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='example@example.com', max_length=50)),
                ('telefon', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zakazivanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField(default='')),
                ('time_end', models.TimeField(default='')),
                ('text', models.TextField(default='text', max_length=900)),
                ('zavrseno', models.BooleanField(default=False)),
                ('dr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appOM.Dr')),
                ('ime_prezime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appOM.Pacijent')),
            ],
        ),
        migrations.CreateModel(
            name='Pacijent_Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_pacijent', models.TextField(default='', max_length=900)),
                ('datee', models.DateTimeField(auto_now_add=True)),
                ('idpacijenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appOM.Pacijent')),
            ],
        ),
        migrations.CreateModel(
            name='Pacijent_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(default='', max_length=50)),
                ('fajl', models.FileField(upload_to='File/pdf')),
                ('imepacijenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOM.Pacijent')),
            ],
        ),
    ]
